# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", 518]
        v.customize ["modifyvm", :id, "--cpus", 1]
        v.customize ["modifyvm", :id, "--cpuexecutioncap", 50]
    end

    config.vm.box = "ubuntu/trusty64"

    config.vm.define :haproxy, primary: true do |config|
        config.vm.hostname = 'haproxy'
        config.vm.communicator = 'ssh'

        config.vm.network :forwarded_port, guest: 8080, host: 8080

        config.vm.provision "provision-docker", type: "shell", path: "../provision-scripts/provision-docker.sh"
        config.vm.provision "provision-containers", type: "shell", path: "provision-containers.sh"
    end
end